/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as SignedOutRouteImport } from './routes/signed-out'
import { Route as SetPasswordRouteImport } from './routes/set-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSecurityRouteImport } from './routes/_authenticated/security'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedCampaignsIndexRouteImport } from './routes/_authenticated/campaigns.index'
import { Route as AuthenticatedMessagesSystemRouteImport } from './routes/_authenticated/messages.system'
import { Route as AuthenticatedMessagesPersonalRouteImport } from './routes/_authenticated/messages.personal'
import { Route as AuthenticatedMessagesNotificationsRouteImport } from './routes/_authenticated/messages.notifications'
import { Route as AuthenticatedInfluencersSearchRouteImport } from './routes/_authenticated/influencers.search'
import { Route as AuthenticatedInfluencersHiredRouteImport } from './routes/_authenticated/influencers.hired'
import { Route as AuthenticatedInfluencersFavoritesRouteImport } from './routes/_authenticated/influencers.favorites'
import { Route as AuthenticatedInfluencersCurrentRouteImport } from './routes/_authenticated/influencers.current'
import { Route as AuthenticatedCampaignsNewRouteImport } from './routes/_authenticated/campaigns.new'
import { Route as AuthenticatedAnalyticsInfluencersRouteImport } from './routes/_authenticated/analytics.influencers'
import { Route as AuthenticatedAnalyticsCampaignsRouteImport } from './routes/_authenticated/analytics.campaigns'
import { Route as AuthenticatedCampaignsPublishIdRouteImport } from './routes/_authenticated/campaigns.publish.$id'
import { Route as AuthenticatedCampaignsPreviewIdRouteImport } from './routes/_authenticated/campaigns.preview.$id'
import { Route as AuthenticatedCampaignsIdEditRouteImport } from './routes/_authenticated/campaigns.$id.edit'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const SignedOutRoute = SignedOutRouteImport.update({
  id: '/signed-out',
  path: '/signed-out',
  getParentRoute: () => rootRouteImport,
} as any)
const SetPasswordRoute = SetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSecurityRoute = AuthenticatedSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCampaignsIndexRoute =
  AuthenticatedCampaignsIndexRouteImport.update({
    id: '/campaigns/',
    path: '/campaigns/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMessagesSystemRoute =
  AuthenticatedMessagesSystemRouteImport.update({
    id: '/messages/system',
    path: '/messages/system',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMessagesPersonalRoute =
  AuthenticatedMessagesPersonalRouteImport.update({
    id: '/messages/personal',
    path: '/messages/personal',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMessagesNotificationsRoute =
  AuthenticatedMessagesNotificationsRouteImport.update({
    id: '/messages/notifications',
    path: '/messages/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInfluencersSearchRoute =
  AuthenticatedInfluencersSearchRouteImport.update({
    id: '/influencers/search',
    path: '/influencers/search',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInfluencersHiredRoute =
  AuthenticatedInfluencersHiredRouteImport.update({
    id: '/influencers/hired',
    path: '/influencers/hired',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInfluencersFavoritesRoute =
  AuthenticatedInfluencersFavoritesRouteImport.update({
    id: '/influencers/favorites',
    path: '/influencers/favorites',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInfluencersCurrentRoute =
  AuthenticatedInfluencersCurrentRouteImport.update({
    id: '/influencers/current',
    path: '/influencers/current',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCampaignsNewRoute =
  AuthenticatedCampaignsNewRouteImport.update({
    id: '/campaigns/new',
    path: '/campaigns/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnalyticsInfluencersRoute =
  AuthenticatedAnalyticsInfluencersRouteImport.update({
    id: '/analytics/influencers',
    path: '/analytics/influencers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnalyticsCampaignsRoute =
  AuthenticatedAnalyticsCampaignsRouteImport.update({
    id: '/analytics/campaigns',
    path: '/analytics/campaigns',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCampaignsPublishIdRoute =
  AuthenticatedCampaignsPublishIdRouteImport.update({
    id: '/campaigns/publish/$id',
    path: '/campaigns/publish/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCampaignsPreviewIdRoute =
  AuthenticatedCampaignsPreviewIdRouteImport.update({
    id: '/campaigns/preview/$id',
    path: '/campaigns/preview/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCampaignsIdEditRoute =
  AuthenticatedCampaignsIdEditRouteImport.update({
    id: '/campaigns/$id/edit',
    path: '/campaigns/$id/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/set-password': typeof SetPasswordRoute
  '/signed-out': typeof SignedOutRoute
  '/welcome': typeof WelcomeRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/security': typeof AuthenticatedSecurityRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/analytics/campaigns': typeof AuthenticatedAnalyticsCampaignsRoute
  '/analytics/influencers': typeof AuthenticatedAnalyticsInfluencersRoute
  '/campaigns/new': typeof AuthenticatedCampaignsNewRoute
  '/influencers/current': typeof AuthenticatedInfluencersCurrentRoute
  '/influencers/favorites': typeof AuthenticatedInfluencersFavoritesRoute
  '/influencers/hired': typeof AuthenticatedInfluencersHiredRoute
  '/influencers/search': typeof AuthenticatedInfluencersSearchRoute
  '/messages/notifications': typeof AuthenticatedMessagesNotificationsRoute
  '/messages/personal': typeof AuthenticatedMessagesPersonalRoute
  '/messages/system': typeof AuthenticatedMessagesSystemRoute
  '/campaigns/': typeof AuthenticatedCampaignsIndexRoute
  '/campaigns/$id/edit': typeof AuthenticatedCampaignsIdEditRoute
  '/campaigns/preview/$id': typeof AuthenticatedCampaignsPreviewIdRoute
  '/campaigns/publish/$id': typeof AuthenticatedCampaignsPublishIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/set-password': typeof SetPasswordRoute
  '/signed-out': typeof SignedOutRoute
  '/welcome': typeof WelcomeRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/security': typeof AuthenticatedSecurityRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/': typeof AuthenticatedIndexRoute
  '/analytics/campaigns': typeof AuthenticatedAnalyticsCampaignsRoute
  '/analytics/influencers': typeof AuthenticatedAnalyticsInfluencersRoute
  '/campaigns/new': typeof AuthenticatedCampaignsNewRoute
  '/influencers/current': typeof AuthenticatedInfluencersCurrentRoute
  '/influencers/favorites': typeof AuthenticatedInfluencersFavoritesRoute
  '/influencers/hired': typeof AuthenticatedInfluencersHiredRoute
  '/influencers/search': typeof AuthenticatedInfluencersSearchRoute
  '/messages/notifications': typeof AuthenticatedMessagesNotificationsRoute
  '/messages/personal': typeof AuthenticatedMessagesPersonalRoute
  '/messages/system': typeof AuthenticatedMessagesSystemRoute
  '/campaigns': typeof AuthenticatedCampaignsIndexRoute
  '/campaigns/$id/edit': typeof AuthenticatedCampaignsIdEditRoute
  '/campaigns/preview/$id': typeof AuthenticatedCampaignsPreviewIdRoute
  '/campaigns/publish/$id': typeof AuthenticatedCampaignsPublishIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/set-password': typeof SetPasswordRoute
  '/signed-out': typeof SignedOutRoute
  '/welcome': typeof WelcomeRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/security': typeof AuthenticatedSecurityRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/analytics/campaigns': typeof AuthenticatedAnalyticsCampaignsRoute
  '/_authenticated/analytics/influencers': typeof AuthenticatedAnalyticsInfluencersRoute
  '/_authenticated/campaigns/new': typeof AuthenticatedCampaignsNewRoute
  '/_authenticated/influencers/current': typeof AuthenticatedInfluencersCurrentRoute
  '/_authenticated/influencers/favorites': typeof AuthenticatedInfluencersFavoritesRoute
  '/_authenticated/influencers/hired': typeof AuthenticatedInfluencersHiredRoute
  '/_authenticated/influencers/search': typeof AuthenticatedInfluencersSearchRoute
  '/_authenticated/messages/notifications': typeof AuthenticatedMessagesNotificationsRoute
  '/_authenticated/messages/personal': typeof AuthenticatedMessagesPersonalRoute
  '/_authenticated/messages/system': typeof AuthenticatedMessagesSystemRoute
  '/_authenticated/campaigns/': typeof AuthenticatedCampaignsIndexRoute
  '/_authenticated/campaigns/$id/edit': typeof AuthenticatedCampaignsIdEditRoute
  '/_authenticated/campaigns/preview/$id': typeof AuthenticatedCampaignsPreviewIdRoute
  '/_authenticated/campaigns/publish/$id': typeof AuthenticatedCampaignsPublishIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/set-password'
    | '/signed-out'
    | '/welcome'
    | '/profile'
    | '/security'
    | '/settings'
    | '/analytics/campaigns'
    | '/analytics/influencers'
    | '/campaigns/new'
    | '/influencers/current'
    | '/influencers/favorites'
    | '/influencers/hired'
    | '/influencers/search'
    | '/messages/notifications'
    | '/messages/personal'
    | '/messages/system'
    | '/campaigns/'
    | '/campaigns/$id/edit'
    | '/campaigns/preview/$id'
    | '/campaigns/publish/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/reset-password'
    | '/set-password'
    | '/signed-out'
    | '/welcome'
    | '/profile'
    | '/security'
    | '/settings'
    | '/'
    | '/analytics/campaigns'
    | '/analytics/influencers'
    | '/campaigns/new'
    | '/influencers/current'
    | '/influencers/favorites'
    | '/influencers/hired'
    | '/influencers/search'
    | '/messages/notifications'
    | '/messages/personal'
    | '/messages/system'
    | '/campaigns'
    | '/campaigns/$id/edit'
    | '/campaigns/preview/$id'
    | '/campaigns/publish/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/reset-password'
    | '/set-password'
    | '/signed-out'
    | '/welcome'
    | '/_authenticated/profile'
    | '/_authenticated/security'
    | '/_authenticated/settings'
    | '/_authenticated/'
    | '/_authenticated/analytics/campaigns'
    | '/_authenticated/analytics/influencers'
    | '/_authenticated/campaigns/new'
    | '/_authenticated/influencers/current'
    | '/_authenticated/influencers/favorites'
    | '/_authenticated/influencers/hired'
    | '/_authenticated/influencers/search'
    | '/_authenticated/messages/notifications'
    | '/_authenticated/messages/personal'
    | '/_authenticated/messages/system'
    | '/_authenticated/campaigns/'
    | '/_authenticated/campaigns/$id/edit'
    | '/_authenticated/campaigns/preview/$id'
    | '/_authenticated/campaigns/publish/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SetPasswordRoute: typeof SetPasswordRoute
  SignedOutRoute: typeof SignedOutRoute
  WelcomeRoute: typeof WelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signed-out': {
      id: '/signed-out'
      path: '/signed-out'
      fullPath: '/signed-out'
      preLoaderRoute: typeof SignedOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/set-password': {
      id: '/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof SetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/security': {
      id: '/_authenticated/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof AuthenticatedSecurityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/campaigns/': {
      id: '/_authenticated/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof AuthenticatedCampaignsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages/system': {
      id: '/_authenticated/messages/system'
      path: '/messages/system'
      fullPath: '/messages/system'
      preLoaderRoute: typeof AuthenticatedMessagesSystemRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages/personal': {
      id: '/_authenticated/messages/personal'
      path: '/messages/personal'
      fullPath: '/messages/personal'
      preLoaderRoute: typeof AuthenticatedMessagesPersonalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages/notifications': {
      id: '/_authenticated/messages/notifications'
      path: '/messages/notifications'
      fullPath: '/messages/notifications'
      preLoaderRoute: typeof AuthenticatedMessagesNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/influencers/search': {
      id: '/_authenticated/influencers/search'
      path: '/influencers/search'
      fullPath: '/influencers/search'
      preLoaderRoute: typeof AuthenticatedInfluencersSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/influencers/hired': {
      id: '/_authenticated/influencers/hired'
      path: '/influencers/hired'
      fullPath: '/influencers/hired'
      preLoaderRoute: typeof AuthenticatedInfluencersHiredRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/influencers/favorites': {
      id: '/_authenticated/influencers/favorites'
      path: '/influencers/favorites'
      fullPath: '/influencers/favorites'
      preLoaderRoute: typeof AuthenticatedInfluencersFavoritesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/influencers/current': {
      id: '/_authenticated/influencers/current'
      path: '/influencers/current'
      fullPath: '/influencers/current'
      preLoaderRoute: typeof AuthenticatedInfluencersCurrentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/campaigns/new': {
      id: '/_authenticated/campaigns/new'
      path: '/campaigns/new'
      fullPath: '/campaigns/new'
      preLoaderRoute: typeof AuthenticatedCampaignsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics/influencers': {
      id: '/_authenticated/analytics/influencers'
      path: '/analytics/influencers'
      fullPath: '/analytics/influencers'
      preLoaderRoute: typeof AuthenticatedAnalyticsInfluencersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics/campaigns': {
      id: '/_authenticated/analytics/campaigns'
      path: '/analytics/campaigns'
      fullPath: '/analytics/campaigns'
      preLoaderRoute: typeof AuthenticatedAnalyticsCampaignsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/campaigns/publish/$id': {
      id: '/_authenticated/campaigns/publish/$id'
      path: '/campaigns/publish/$id'
      fullPath: '/campaigns/publish/$id'
      preLoaderRoute: typeof AuthenticatedCampaignsPublishIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/campaigns/preview/$id': {
      id: '/_authenticated/campaigns/preview/$id'
      path: '/campaigns/preview/$id'
      fullPath: '/campaigns/preview/$id'
      preLoaderRoute: typeof AuthenticatedCampaignsPreviewIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/campaigns/$id/edit': {
      id: '/_authenticated/campaigns/$id/edit'
      path: '/campaigns/$id/edit'
      fullPath: '/campaigns/$id/edit'
      preLoaderRoute: typeof AuthenticatedCampaignsIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSecurityRoute: typeof AuthenticatedSecurityRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAnalyticsCampaignsRoute: typeof AuthenticatedAnalyticsCampaignsRoute
  AuthenticatedAnalyticsInfluencersRoute: typeof AuthenticatedAnalyticsInfluencersRoute
  AuthenticatedCampaignsNewRoute: typeof AuthenticatedCampaignsNewRoute
  AuthenticatedInfluencersCurrentRoute: typeof AuthenticatedInfluencersCurrentRoute
  AuthenticatedInfluencersFavoritesRoute: typeof AuthenticatedInfluencersFavoritesRoute
  AuthenticatedInfluencersHiredRoute: typeof AuthenticatedInfluencersHiredRoute
  AuthenticatedInfluencersSearchRoute: typeof AuthenticatedInfluencersSearchRoute
  AuthenticatedMessagesNotificationsRoute: typeof AuthenticatedMessagesNotificationsRoute
  AuthenticatedMessagesPersonalRoute: typeof AuthenticatedMessagesPersonalRoute
  AuthenticatedMessagesSystemRoute: typeof AuthenticatedMessagesSystemRoute
  AuthenticatedCampaignsIndexRoute: typeof AuthenticatedCampaignsIndexRoute
  AuthenticatedCampaignsIdEditRoute: typeof AuthenticatedCampaignsIdEditRoute
  AuthenticatedCampaignsPreviewIdRoute: typeof AuthenticatedCampaignsPreviewIdRoute
  AuthenticatedCampaignsPublishIdRoute: typeof AuthenticatedCampaignsPublishIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSecurityRoute: AuthenticatedSecurityRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAnalyticsCampaignsRoute: AuthenticatedAnalyticsCampaignsRoute,
  AuthenticatedAnalyticsInfluencersRoute:
    AuthenticatedAnalyticsInfluencersRoute,
  AuthenticatedCampaignsNewRoute: AuthenticatedCampaignsNewRoute,
  AuthenticatedInfluencersCurrentRoute: AuthenticatedInfluencersCurrentRoute,
  AuthenticatedInfluencersFavoritesRoute:
    AuthenticatedInfluencersFavoritesRoute,
  AuthenticatedInfluencersHiredRoute: AuthenticatedInfluencersHiredRoute,
  AuthenticatedInfluencersSearchRoute: AuthenticatedInfluencersSearchRoute,
  AuthenticatedMessagesNotificationsRoute:
    AuthenticatedMessagesNotificationsRoute,
  AuthenticatedMessagesPersonalRoute: AuthenticatedMessagesPersonalRoute,
  AuthenticatedMessagesSystemRoute: AuthenticatedMessagesSystemRoute,
  AuthenticatedCampaignsIndexRoute: AuthenticatedCampaignsIndexRoute,
  AuthenticatedCampaignsIdEditRoute: AuthenticatedCampaignsIdEditRoute,
  AuthenticatedCampaignsPreviewIdRoute: AuthenticatedCampaignsPreviewIdRoute,
  AuthenticatedCampaignsPublishIdRoute: AuthenticatedCampaignsPublishIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SetPasswordRoute: SetPasswordRoute,
  SignedOutRoute: SignedOutRoute,
  WelcomeRoute: WelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
